# Spring Properties
spring:
  application:
    name: eureka-client

# Discovery Server Access
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 8762